version: '3.7'

networks:
  project:
    driver: bridge
  proxy:
    external:
      name: local-network

volumes:
  data:
    name: comptes_data

services:
  php:
    image: proprietesprivees/web:7.2
    container_name: comptes_php
    restart: on-failure
    volumes:
      - ./:/var/www/html:cached
      - ./docker/php-fpm/custom-php-fpm.conf:/usr/local/etc/php-fpm.d/custom-php-fpm.conf
      - ./docker/php-fpm/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
      - ./docker/logs/php-fpm:/var/log/php-fpm
    networks:
      - project

  nginx:
    image: nginx:1-alpine
    container_name: comptes_nginx
    restart: on-failure
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs/nginx:/var/log/nginx
    labels:
      # These labels are used by Traefik reverse proxy
      - traefik.frontend.rule=Host:comptes.loc
      - traefik.docker.network=local-network
    depends_on:
      - php
    networks:
      - project
      - proxy

  mysql:
    image: mysql:5.7
    container_name: comptes_mysql
    restart: on-failure
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=comptes
      - MYSQL_ROOT_PASSWORD=root
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - project

  adminer:
    image: adminer
    container_name: comptes_adminer
    restart: on-failure
    volumes:
      - ./docker/adminer/plugins-enabled:/var/www/html/plugins-enabled
    labels:
      # These labels are used by Traefik reverse proxy
      - traefik.frontend.rule=Host:adminer.comptes.loc
      - traefik.docker.network=local-network
    depends_on:
      - mysql
    networks:
      - project
      - proxy
