version: '3.7'

networks:
  web:
    external:
      name: web
  project:
    driver: bridge

services:
  php:
    image: proprietesprivees/web:7.2
    container_name: comptes_php
    restart: on-failure
    volumes:
      - ./:/var/www/html:cached
      - ./docker/php-fpm/custom-php-fpm.conf:/usr/local/etc/php-fpm.d/custom-php-fpm.conf
      - ./docker/php-fpm/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
      - ./docker/logs/php-fpm:/var/log/php-fpm
    networks:
      - web
      - project

  nginx:
    image: nginx:1-alpine
    container_name: comptes_nginx
    restart: on-failure
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs/nginx:/var/log/nginx
    labels:
      - "traefik.http.routers.comptes.rule=Host(`comptes.loc`)"
    depends_on:
      - php
    networks:
      - web
      - project
