<?php

namespace Comptes\Bundle\CoreBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Comptes\Bundle\CoreBundle\Entity\Categorie;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository
{
    /**
     * {@inheritDoc}
     */
    public function findAll()
    {
        return $this->findBy(array(), array('rang' => 'ASC'));
    }

    /**
     * Calcul le montant cumulé des mouvements d'une catégorie.
     *
     * @param Categorie $categorie La catégorie.
     * @return float
     */
    public function getMontantTotal(Categorie $categorie)
    {
        // Calcul du montant total des mouvements de la catégorie
        $queryBuilder = $this->_em->createQueryBuilder();

        // La liste des catégories de mouvements
        $categorieID = $categorie->getId();
        $categories = array($categorieID);
        $categoriesFilles = $categorie->getCategoriesFillesRecursive();

        foreach ($categoriesFilles as $categorieFille)
        {
            $categories[] = $categorieFille->getId();
        }

        $queryBuilder
            ->select('SUM(m.montant) AS total')
            ->from('ComptesCoreBundle:Mouvement', 'm')
            ->where('m.categorie in (:categories)')
            ->setParameter('categories', $categories);

        $result = $queryBuilder->getQuery()->getSingleResult();

        $montant = $result['total'] !== null ? $result['total'] : 0;

        return $montant;
    }
}